//! The web assets, compiled into the binary, plus the two classifications
//! every lookup needs: is this path safe, and may an untrusted layer serve it.
//!
//! `ASSETS` is generated by build.rs from `static/`.

include!(concat!(env!("OUT_DIR"), "/assets_table.rs"));

/// Rejects anything that is not a plain relative path.
///
/// The filesystem layers get their confinement from `canonicalize()` +
/// `starts_with(base)`, but the embedded table has no filesystem to
/// canonicalize against, so it needs its own guard. Applied *before* any
/// layer is consulted, so a traversal attempt 404s identically whether or
/// not a filesystem layer is configured — otherwise the difference would
/// reveal which layers are live.
pub fn normalize(rel: &str) -> Option<&str> {
    if rel.is_empty() || rel.starts_with('/') || rel.contains('\\') {
        return None;
    }
    for seg in rel.split('/') {
        if seg.is_empty() || seg == "." || seg == ".." {
            return None;
        }
    }
    Some(rel)
}

pub fn get(rel: &str) -> Option<&'static [u8]> {
    let rel = normalize(rel)?;
    ASSETS.binary_search_by(|(k, _)| (*k).cmp(rel)).ok().map(|i| ASSETS[i].1)
}

/// What authority a layer needs to serve a path.
///
/// JavaScript served from `/static/` runs same-origin with every terminal
/// websocket this server owns, so whoever can replace it can drive every
/// shell. CSS and images cannot. That asymmetry — not file type as such —
/// is what this enum encodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Class {
    /// Replaceable by a project or by the user directory.
    Theme,
    /// Replaceable only by the operator, via `$ROOST_STATIC`.
    Code,
}

const THEME_EXT: &[&str] = &[
    "css", "svg", "png", "jpg", "jpeg", "gif", "webp", "ico", "woff", "woff2", "ttf", "otf",
];

/// The single answer to "what is this path's extension?", lowercased.
///
/// `class_of` (below) and `routes::content_type` both have to answer that
/// question about the same `rel`, and they used to do it two different ways
/// — `class_of` split on the final `.` in the last path segment, while
/// `content_type` used `Path::extension()`, which is case-preserving and
/// returns `None` for a leading-dot name like `".css"`. The two disagreeing
/// is not a security hole (nothing here grants script-executing authority on
/// a mismatch), but it is a functional one: this branch also sends
/// `X-Content-Type-Options: nosniff` on every 200, and a stylesheet served
/// with the wrong MIME type is outright blocked by Fetch's nosniff rule
/// rather than sniffed and recovered. Routing both functions through one
/// helper makes that class of drift impossible to reintroduce.
pub fn ext_of(rel: &str) -> String {
    rel.rsplit('/').next().unwrap_or("").rsplit_once('.').map(|(_, e)| e.to_ascii_lowercase()).unwrap_or_default()
}

pub fn class_of(rel: &str) -> Class {
    // Both deny-by-default cases land in Code, by different routes: "README"
    // has no dot at all, so `ext_of` returns "", which is not in THEME_EXT;
    // ".gitignore" splits as ("", "gitignore"), so `ext_of` returns
    // "gitignore" — a real extension, just not a theme one. Neither is
    // special-cased, and neither needs to be.
    if THEME_EXT.contains(&ext_of(rel).as_str()) {
        Class::Theme
    } else {
        Class::Code
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_carries_the_real_files() {
        let js = get("app.js").expect("app.js must be embedded");
        let disk = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/static/app.js")).unwrap();
        assert_eq!(js, &disk[..], "embedded bytes must match the file on disk");
        assert!(get("style.css").is_some());
        assert!(get("themes/darcula.css").is_some(), "nested paths must be reachable");
        assert!(get("vendor/xterm.js").is_some());
        assert!(get("nope.js").is_none());
    }

    /// Walks `static/` on disk at test time and checks every file it finds
    /// is in `ASSETS` with byte-identical content, and that the counts
    /// match too (so a file present on disk but silently dropped by
    /// build.rs — the failure mode `.flatten()` used to hide, see build.rs
    /// — cannot pass by merely being unmentioned). This subsumes the four
    /// hand-named files in `the_table_carries_the_real_files` above; kept
    /// separate from it because that test also exercises `get`'s normal
    /// lookup path, not just table completeness.
    #[test]
    fn every_file_on_disk_is_embedded_byte_identical() {
        fn walk(root: &std::path::Path, dir: &std::path::Path, out: &mut Vec<String>) {
            for e in std::fs::read_dir(dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display())) {
                let e = e.unwrap_or_else(|e| panic!("read entry in {}: {e}", dir.display()));
                let p = e.path();
                if p.is_dir() {
                    walk(root, &p, out);
                } else {
                    out.push(p.strip_prefix(root).expect("under root").to_string_lossy().replace('\\', "/"));
                }
            }
        }
        let root = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static"));
        let mut on_disk = Vec::new();
        walk(&root, &root, &mut on_disk);

        assert_eq!(
            on_disk.len(),
            ASSETS.len(),
            "static/ has {} files but ASSETS has {} entries — build.rs dropped or duplicated one",
            on_disk.len(),
            ASSETS.len()
        );
        for rel in &on_disk {
            let disk = std::fs::read(root.join(rel)).unwrap();
            let embedded = get(rel).unwrap_or_else(|| panic!("{rel} is on disk but missing from ASSETS"));
            assert_eq!(embedded, &disk[..], "{rel}: embedded bytes must match the file on disk");
        }
    }

    /// Every theme must define `--warn`, and define it *legibly* against its
    /// own `--bg`.
    ///
    /// Asserting the contrast rather than the mere presence of the variable,
    /// because presence is the assertion that would have passed while the bug
    /// was live: `--warn` was defined in no theme at all, so all four of
    /// style.css's `var(--warn, #d79921)` sites fell back to one hardcoded
    /// gruvbox yellow. That reads fine on the four dark themes and sits at
    /// 2.48:1 on light.css's white — below WCAG AA (4.5:1) and below even
    /// AA-large (3.0:1) — for `.savestate.warn`, which is 11px text saying a
    /// write is being withheld. A presence check would also pass for a new
    /// theme that defines `--warn` as something unreadable, which is the same
    /// defect wearing a different hat.
    ///
    /// Revert-checked: dropping the `--warn` line from light.css alone fails
    /// this with "light.css: --warn is not defined"; setting it back to
    /// #d79921 fails with the 2.48 ratio.
    /// The bridge (`static/daisy-bridge.css`) is what makes a daisyUI theme reach
    /// roost's own stylesheet: it must define every variable a roost theme
    /// file defines, or the missing one silently falls back to whatever
    /// `var(--x, fallback)` says at each site. dark.css is the reference set.
    /// It must also re-declare `--border`, which daisyUI's themes file sets
    /// to a *width* on every theme and roost reads as a colour.
    #[test]
    fn the_daisyui_bridge_defines_every_roost_theme_variable() {
        let names = |css: &str| -> Vec<String> {
            let mut v: Vec<String> = css
                .split("--")
                .skip(1)
                .filter_map(|rest| rest.split(':').next().map(|n| n.trim().to_string()))
                .filter(|n| !n.is_empty() && n.chars().all(|c| c.is_ascii_alphanumeric() || c == '-'))
                .collect();
            v.sort();
            v.dedup();
            v
        };
        let reference = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/static/themes/dark.css")).unwrap();
        let bridge = std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/static/daisy-bridge.css"))
            .expect("static/daisy-bridge.css missing");
        let have = names(&bridge);
        let missing: Vec<String> = names(&reference).into_iter().filter(|n| !have.contains(n)).collect();
        assert!(missing.is_empty(), "the bridge does not define: {missing:?}");
        assert!(get("vendor/daisyui-themes.css").is_some(), "daisyUI themes not embedded");
        assert!(get("daisy-bridge.css").is_some(), "bridge not embedded");
    }

    #[test]
    fn every_theme_defines_a_legible_warn_colour() {
        /// WCAG 2.x relative luminance.
        fn lum(hex: &str) -> f64 {
            let c = |i: usize| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex pair") as f64 / 255.0;
            let f = |v: f64| if v <= 0.04045 { v / 12.92 } else { ((v + 0.055) / 1.055).powf(2.4) };
            0.2126 * f(c(1)) + 0.7152 * f(c(3)) + 0.0722 * f(c(5))
        }
        /// The `--name: #rrggbb` value from a theme's text, if present.
        fn var_of(css: &str, name: &str) -> Option<String> {
            let at = css.find(&format!("{name}:"))? + name.len() + 1;
            let rest = css[at..].trim_start();
            let hex: String = rest.chars().take_while(|c| *c == '#' || c.is_ascii_alphanumeric()).collect();
            (hex.len() == 7 && hex.starts_with('#')).then_some(hex)
        }

        let dir = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static/themes"));
        let mut checked = 0;
        for e in std::fs::read_dir(&dir).expect("themes dir") {
            let p = e.expect("theme entry").path();
            if p.extension().and_then(|s| s.to_str()) != Some("css") {
                continue;
            }
            let name = p.file_name().expect("file name").to_string_lossy().into_owned();
            let css = std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{name}: {e}"));
            let warn = var_of(&css, "--warn").unwrap_or_else(|| panic!("{name}: --warn is not defined"));
            let bg = var_of(&css, "--bg").unwrap_or_else(|| panic!("{name}: --bg is not defined"));
            let (a, b) = (lum(&warn), lum(&bg));
            let (hi, lo) = if a > b { (a, b) } else { (b, a) };
            let ratio = (hi + 0.05) / (lo + 0.05);
            assert!(
                ratio >= 4.5,
                "{name}: --warn {warn} on --bg {bg} is {ratio:.2}:1, below WCAG AA 4.5:1 \
                 (.savestate.warn is 11px text)"
            );
            checked += 1;
        }
        // Or a rename of the directory turns this into a test that asserts
        // nothing and passes — the vacuous-green failure mode CLAUDE.md is
        // explicit about.
        assert!(checked >= 5, "expected every theme to be checked, saw {checked}");
    }

    #[test]
    fn the_table_is_sorted_so_binary_search_is_valid() {
        let keys: Vec<&str> = ASSETS.iter().map(|(k, _)| *k).collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted, "build.rs must emit a sorted table");
    }

    #[test]
    fn normalize_rejects_every_way_out_of_the_tree() {
        assert!(normalize("app.js").is_some());
        assert!(normalize("themes/dark.css").is_some());
        assert_eq!(normalize(""), None);
        assert_eq!(normalize("/etc/passwd"), None);
        assert_eq!(normalize("../Cargo.toml"), None);
        assert_eq!(normalize("themes/../../Cargo.toml"), None);
        assert_eq!(normalize("./app.js"), None);
        assert_eq!(normalize("a//b.css"), None);
        assert_eq!(normalize("a\\..\\b"), None);
        // and the same guard covers `get`
        assert!(get("../Cargo.toml").is_none());
    }

    /// Class decides which layers may answer for a path, so an unrecognised
    /// extension MUST land in Code. Deny-by-default means widening the
    /// overridable set is an edit to THEME_EXT, never a side effect of
    /// someone dropping an unfamiliar file into a theme directory.
    #[test]
    fn unknown_and_executable_extensions_are_code() {
        assert_eq!(class_of("style.css"), Class::Theme);
        assert_eq!(class_of("themes/darcula.css"), Class::Theme);
        assert_eq!(class_of("logo.PNG"), Class::Theme, "extension match is case-insensitive");
        assert_eq!(class_of("Inter.woff2"), Class::Theme);
        assert_eq!(class_of("icons.svg"), Class::Theme);

        assert_eq!(class_of("app.js"), Class::Code);
        assert_eq!(class_of("vendor/xterm.js"), Class::Code);
        assert_eq!(class_of("index.html"), Class::Code);
        assert_eq!(class_of("thing.wasm"), Class::Code);
        // the deny-by-default cases
        assert_eq!(class_of("README"), Class::Code, "no extension is not a theme asset");
        assert_eq!(class_of(".gitignore"), Class::Code, "a dotfile's name is not an extension");
        assert_eq!(class_of("data.json"), Class::Code, "unrecognised extension defaults to code");
        assert_eq!(class_of("evil.js.css.js"), Class::Code, "only the LAST extension counts");
        assert_eq!(class_of("css"), Class::Code, "a bare word is not an extension");
    }
}
