//! The web assets, compiled into the binary, plus the two classifications
//! every lookup needs: is this path safe, and may an untrusted layer serve it.
//!
//! `ASSETS` is generated by build.rs from `static/`.

include!(concat!(env!("OUT_DIR"), "/assets_table.rs"));

/// Rejects anything that is not a plain relative path.
///
/// The filesystem layers get their confinement from `canonicalize()` +
/// `starts_with(base)`, but the embedded table has no filesystem to
/// canonicalize against, so it needs its own guard. Applied *before* any
/// layer is consulted, so a traversal attempt 404s identically whether or
/// not a filesystem layer is configured — otherwise the difference would
/// reveal which layers are live.
pub fn normalize(rel: &str) -> Option<&str> {
    if rel.is_empty() || rel.starts_with('/') || rel.contains('\\') {
        return None;
    }
    for seg in rel.split('/') {
        if seg.is_empty() || seg == "." || seg == ".." {
            return None;
        }
    }
    Some(rel)
}

pub fn get(rel: &str) -> Option<&'static [u8]> {
    let rel = normalize(rel)?;
    ASSETS.binary_search_by(|(k, _)| (*k).cmp(rel)).ok().map(|i| ASSETS[i].1)
}

/// What authority a layer needs to serve a path.
///
/// JavaScript served from `/static/` runs same-origin with every terminal
/// websocket this server owns, so whoever can replace it can drive every
/// shell. CSS and images cannot. That asymmetry — not file type as such —
/// is what this enum encodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Class {
    /// Replaceable by a project or by the user directory.
    Theme,
    /// Replaceable only by the operator, via `$RESH_STATIC`.
    Code,
}

const THEME_EXT: &[&str] = &[
    "css", "svg", "png", "jpg", "jpeg", "gif", "webp", "ico", "woff", "woff2", "ttf", "otf",
];

pub fn class_of(rel: &str) -> Class {
    let name = rel.rsplit('/').next().unwrap_or("");
    // `rsplit_once`, so only the final extension counts: "evil.css.js" is js.
    // A leading dot yields an empty stem (".gitignore" -> ("", "gitignore")),
    // which is not in THEME_EXT and so lands in Code, as intended.
    let ext = match name.rsplit_once('.') {
        Some((_, e)) => e.to_ascii_lowercase(),
        None => return Class::Code,
    };
    if THEME_EXT.contains(&ext.as_str()) {
        Class::Theme
    } else {
        Class::Code
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_carries_the_real_files() {
        let js = get("app.js").expect("app.js must be embedded");
        let disk = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/static/app.js")).unwrap();
        assert_eq!(js, &disk[..], "embedded bytes must match the file on disk");
        assert!(get("style.css").is_some());
        assert!(get("themes/darcula.css").is_some(), "nested paths must be reachable");
        assert!(get("vendor/xterm.js").is_some());
        assert!(get("nope.js").is_none());
    }

    #[test]
    fn the_table_is_sorted_so_binary_search_is_valid() {
        let keys: Vec<&str> = ASSETS.iter().map(|(k, _)| *k).collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted, "build.rs must emit a sorted table");
    }

    #[test]
    fn normalize_rejects_every_way_out_of_the_tree() {
        assert!(normalize("app.js").is_some());
        assert!(normalize("themes/dark.css").is_some());
        assert_eq!(normalize(""), None);
        assert_eq!(normalize("/etc/passwd"), None);
        assert_eq!(normalize("../Cargo.toml"), None);
        assert_eq!(normalize("themes/../../Cargo.toml"), None);
        assert_eq!(normalize("./app.js"), None);
        assert_eq!(normalize("a//b.css"), None);
        assert_eq!(normalize("a\\..\\b"), None);
        // and the same guard covers `get`
        assert!(get("../Cargo.toml").is_none());
    }

    /// Class decides which layers may answer for a path, so an unrecognised
    /// extension MUST land in Code. Deny-by-default means widening the
    /// overridable set is an edit to THEME_EXT, never a side effect of
    /// someone dropping an unfamiliar file into a theme directory.
    #[test]
    fn unknown_and_executable_extensions_are_code() {
        assert_eq!(class_of("style.css"), Class::Theme);
        assert_eq!(class_of("themes/darcula.css"), Class::Theme);
        assert_eq!(class_of("logo.PNG"), Class::Theme, "extension match is case-insensitive");
        assert_eq!(class_of("Inter.woff2"), Class::Theme);
        assert_eq!(class_of("icons.svg"), Class::Theme);

        assert_eq!(class_of("app.js"), Class::Code);
        assert_eq!(class_of("vendor/xterm.js"), Class::Code);
        assert_eq!(class_of("index.html"), Class::Code);
        assert_eq!(class_of("thing.wasm"), Class::Code);
        // the deny-by-default cases
        assert_eq!(class_of("README"), Class::Code, "no extension is not a theme asset");
        assert_eq!(class_of(".gitignore"), Class::Code, "a dotfile's name is not an extension");
        assert_eq!(class_of("data.json"), Class::Code, "unrecognised extension defaults to code");
        assert_eq!(class_of("evil.js.css.js"), Class::Code, "only the LAST extension counts");
        assert_eq!(class_of("css"), Class::Code, "a bare word is not an extension");
    }
}
