//! The web assets, compiled into the binary, plus the two classifications
//! every lookup needs: is this path safe, and may an untrusted layer serve it.
//!
//! `ASSETS` is generated by build.rs from `static/`.

include!(concat!(env!("OUT_DIR"), "/assets_table.rs"));

/// Rejects anything that is not a plain relative path.
///
/// The filesystem layers get their confinement from `canonicalize()` +
/// `starts_with(base)`, but the embedded table has no filesystem to
/// canonicalize against, so it needs its own guard. Applied *before* any
/// layer is consulted, so a traversal attempt 404s identically whether or
/// not a filesystem layer is configured — otherwise the difference would
/// reveal which layers are live.
pub fn normalize(rel: &str) -> Option<&str> {
    if rel.is_empty() || rel.starts_with('/') || rel.contains('\\') {
        return None;
    }
    for seg in rel.split('/') {
        if seg.is_empty() || seg == "." || seg == ".." {
            return None;
        }
    }
    Some(rel)
}

pub fn get(rel: &str) -> Option<&'static [u8]> {
    let rel = normalize(rel)?;
    ASSETS.binary_search_by(|(k, _)| (*k).cmp(rel)).ok().map(|i| ASSETS[i].1)
}

/// What authority a layer needs to serve a path.
///
/// JavaScript served from `/static/` runs same-origin with every terminal
/// websocket this server owns, so whoever can replace it can drive every
/// shell. CSS and images cannot. That asymmetry — not file type as such —
/// is what this enum encodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Class {
    /// Replaceable by a project or by the user directory.
    Theme,
    /// Replaceable only by the operator, via `$RESH_STATIC`.
    Code,
}

const THEME_EXT: &[&str] = &[
    "css", "svg", "png", "jpg", "jpeg", "gif", "webp", "ico", "woff", "woff2", "ttf", "otf",
];

/// The single answer to "what is this path's extension?", lowercased.
///
/// `class_of` (below) and `routes::content_type` both have to answer that
/// question about the same `rel`, and they used to do it two different ways
/// — `class_of` split on the final `.` in the last path segment, while
/// `content_type` used `Path::extension()`, which is case-preserving and
/// returns `None` for a leading-dot name like `".css"`. The two disagreeing
/// is not a security hole (nothing here grants script-executing authority on
/// a mismatch), but it is a functional one: this branch also sends
/// `X-Content-Type-Options: nosniff` on every 200, and a stylesheet served
/// with the wrong MIME type is outright blocked by Fetch's nosniff rule
/// rather than sniffed and recovered. Routing both functions through one
/// helper makes that class of drift impossible to reintroduce.
pub fn ext_of(rel: &str) -> String {
    rel.rsplit('/').next().unwrap_or("").rsplit_once('.').map(|(_, e)| e.to_ascii_lowercase()).unwrap_or_default()
}

pub fn class_of(rel: &str) -> Class {
    // An empty extension covers both "no dot at all" (README) and "the dot
    // is the whole name" (.gitignore) — `ext_of` returns "" for both, and
    // "" is not in THEME_EXT, so both land in Code, as intended.
    if THEME_EXT.contains(&ext_of(rel).as_str()) {
        Class::Theme
    } else {
        Class::Code
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_table_carries_the_real_files() {
        let js = get("app.js").expect("app.js must be embedded");
        let disk = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/static/app.js")).unwrap();
        assert_eq!(js, &disk[..], "embedded bytes must match the file on disk");
        assert!(get("style.css").is_some());
        assert!(get("themes/darcula.css").is_some(), "nested paths must be reachable");
        assert!(get("vendor/xterm.js").is_some());
        assert!(get("nope.js").is_none());
    }

    /// Walks `static/` on disk at test time and checks every file it finds
    /// is in `ASSETS` with byte-identical content, and that the counts
    /// match too (so a file present on disk but silently dropped by
    /// build.rs — the failure mode `.flatten()` used to hide, see build.rs
    /// — cannot pass by merely being unmentioned). This subsumes the four
    /// hand-named files in `the_table_carries_the_real_files` above; kept
    /// separate from it because that test also exercises `get`'s normal
    /// lookup path, not just table completeness.
    #[test]
    fn every_file_on_disk_is_embedded_byte_identical() {
        fn walk(root: &std::path::Path, dir: &std::path::Path, out: &mut Vec<String>) {
            for e in std::fs::read_dir(dir).unwrap_or_else(|e| panic!("read {}: {e}", dir.display())) {
                let e = e.unwrap_or_else(|e| panic!("read entry in {}: {e}", dir.display()));
                let p = e.path();
                if p.is_dir() {
                    walk(root, &p, out);
                } else {
                    out.push(p.strip_prefix(root).expect("under root").to_string_lossy().replace('\\', "/"));
                }
            }
        }
        let root = std::path::PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/static"));
        let mut on_disk = Vec::new();
        walk(&root, &root, &mut on_disk);

        assert_eq!(
            on_disk.len(),
            ASSETS.len(),
            "static/ has {} files but ASSETS has {} entries — build.rs dropped or duplicated one",
            on_disk.len(),
            ASSETS.len()
        );
        for rel in &on_disk {
            let disk = std::fs::read(root.join(rel)).unwrap();
            let embedded = get(rel).unwrap_or_else(|| panic!("{rel} is on disk but missing from ASSETS"));
            assert_eq!(embedded, &disk[..], "{rel}: embedded bytes must match the file on disk");
        }
    }

    #[test]
    fn the_table_is_sorted_so_binary_search_is_valid() {
        let keys: Vec<&str> = ASSETS.iter().map(|(k, _)| *k).collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted, "build.rs must emit a sorted table");
    }

    #[test]
    fn normalize_rejects_every_way_out_of_the_tree() {
        assert!(normalize("app.js").is_some());
        assert!(normalize("themes/dark.css").is_some());
        assert_eq!(normalize(""), None);
        assert_eq!(normalize("/etc/passwd"), None);
        assert_eq!(normalize("../Cargo.toml"), None);
        assert_eq!(normalize("themes/../../Cargo.toml"), None);
        assert_eq!(normalize("./app.js"), None);
        assert_eq!(normalize("a//b.css"), None);
        assert_eq!(normalize("a\\..\\b"), None);
        // and the same guard covers `get`
        assert!(get("../Cargo.toml").is_none());
    }

    /// Class decides which layers may answer for a path, so an unrecognised
    /// extension MUST land in Code. Deny-by-default means widening the
    /// overridable set is an edit to THEME_EXT, never a side effect of
    /// someone dropping an unfamiliar file into a theme directory.
    #[test]
    fn unknown_and_executable_extensions_are_code() {
        assert_eq!(class_of("style.css"), Class::Theme);
        assert_eq!(class_of("themes/darcula.css"), Class::Theme);
        assert_eq!(class_of("logo.PNG"), Class::Theme, "extension match is case-insensitive");
        assert_eq!(class_of("Inter.woff2"), Class::Theme);
        assert_eq!(class_of("icons.svg"), Class::Theme);

        assert_eq!(class_of("app.js"), Class::Code);
        assert_eq!(class_of("vendor/xterm.js"), Class::Code);
        assert_eq!(class_of("index.html"), Class::Code);
        assert_eq!(class_of("thing.wasm"), Class::Code);
        // the deny-by-default cases
        assert_eq!(class_of("README"), Class::Code, "no extension is not a theme asset");
        assert_eq!(class_of(".gitignore"), Class::Code, "a dotfile's name is not an extension");
        assert_eq!(class_of("data.json"), Class::Code, "unrecognised extension defaults to code");
        assert_eq!(class_of("evil.js.css.js"), Class::Code, "only the LAST extension counts");
        assert_eq!(class_of("css"), Class::Code, "a bare word is not an extension");
    }
}
